// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainDezhApp.Services;

#nullable disable

namespace TrainDezhApp.Migrations
{
    [DbContext(typeof(TrainDezhDbContext))]
    [Migration("20250603082351_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainDezhApp.Models.Accident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Equipment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Investigation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("accidents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3892),
                            Description = "Сход вагона на км 15",
                            Location = "км 15",
                            OccurredAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3892),
                            ReportedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3892),
                            Severity = "Критическая",
                            Status = "Расследуется"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3900),
                            Description = "Неисправность светофора",
                            Equipment = "Светофор №12",
                            Location = "км 25",
                            OccurredAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3900),
                            ReportedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3900),
                            Severity = "Средняя",
                            Status = "Устранена"
                        });
                });

            modelBuilder.Entity("TrainDezhApp.Models.DatabaseSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionTimeout")
                        .HasColumnType("integer");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<bool>("UseSSL")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("database_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectionTimeout = 30,
                            Database = "train_dezh",
                            Host = "localhost",
                            LastUpdated = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3705),
                            Password = "",
                            Port = 5432,
                            UseSSL = false,
                            Username = "postgres"
                        });
                });

            modelBuilder.Entity("TrainDezhApp.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("MinQuantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Supplier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Status");

                    b.ToTable("materials", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Запчасти",
                            LastUpdated = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3922),
                            MinQuantity = 5m,
                            Name = "Тормозные колодки",
                            Price = 2500.00m,
                            Quantity = 15m,
                            Status = "В наличии",
                            Unit = "шт"
                        },
                        new
                        {
                            Id = 2,
                            Category = "ГСМ",
                            LastUpdated = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(4004),
                            MinQuantity = 10m,
                            Name = "Масло моторное",
                            Price = 450.00m,
                            Quantity = 3m,
                            Status = "Заканчивается",
                            Unit = "л"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Крепеж",
                            LastUpdated = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(4007),
                            MinQuantity = 20m,
                            Name = "Болты М12",
                            Price = 15.00m,
                            Quantity = 100m,
                            Status = "В наличии",
                            Unit = "шт"
                        });
                });

            modelBuilder.Entity("TrainDezhApp.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Priority");

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("TrainDezhApp.Models.ShiftHandover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentTasks")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EquipmentStatus")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("HandoverTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImportantNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("IncomingOfficer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OutgoingOfficer")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SafetyIssues")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Signature")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftDate");

                    b.HasIndex("ShiftType");

                    b.ToTable("shift_handovers", (string)null);
                });

            modelBuilder.Entity("TrainDezhApp.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsOnShift")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Отдел Г",
                            EmployeeNumber = "001",
                            FirstName = "Иван",
                            HiredAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3826),
                            IsOnShift = true,
                            LastName = "Петров",
                            Position = "Дежурный по станции",
                            Status = "Активен"
                        },
                        new
                        {
                            Id = 2,
                            Department = "Отдел Г",
                            EmployeeNumber = "002",
                            FirstName = "Мария",
                            HiredAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3835),
                            IsOnShift = true,
                            LastName = "Сидорова",
                            Position = "Машинист",
                            Status = "Активен"
                        },
                        new
                        {
                            Id = 3,
                            Department = "Отдел Г",
                            EmployeeNumber = "003",
                            FirstName = "Алексей",
                            HiredAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3836),
                            IsOnShift = false,
                            LastName = "Козлов",
                            Position = "Слесарь",
                            Status = "Активен"
                        });
                });

            modelBuilder.Entity("TrainDezhApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(5012),
                            FullName = "Администратор",
                            IsActive = true,
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Role = 1,
                            Username = "root"
                        });
                });

            modelBuilder.Entity("TrainDezhApp.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Equipment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("works", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedTo = "Козлов А.",
                            CreatedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3860),
                            Equipment = "Локомотив №1234",
                            Priority = "Средний",
                            Status = "Выполняется",
                            Title = "Плановое ТО локомотива №1234"
                        },
                        new
                        {
                            Id = 2,
                            AssignedTo = "Сидорова М.",
                            CreatedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3867),
                            Equipment = "Вагон №5678",
                            Priority = "Низкий",
                            Status = "Завершено",
                            Title = "Замена тормозных колодок"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 3, 8, 23, 50, 963, DateTimeKind.Utc).AddTicks(3868),
                            Location = "км 25",
                            Priority = "Высокий",
                            Status = "Новая",
                            Title = "Ремонт светофора"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
